#!/usr/bin/ruby

# lulu 5.5x8.5 digest size, without full bleed
# from lulu's readme file for digest size:
  doc_h = 8.75
  doc_w = 5.625
  trim_h = 8.5
  trim_w = 5.5

outside_trim = doc_w-trim_w
tb_trim = (doc_h-trim_h)/2
gutter = 0.25 # not sure if this is exactly right; based on http://tex.stackexchange.com/questions/80520/does-documentclassbook-by-default-take-care-of-gutter-for-inner-side-of-page

margin_t = 0.5
margin_b = 0.92
margin_outside = 0.5
margin_inside = 0.5
headsep = 0.22
headheight = 0.11

def set(name,length)
  print "  \\setlength{\\#{name}}{#{length}in}\n"
end

print "% The following were generated by compute_layout.rb and are to be cut and pasted into poets.cls:\n"

# see LaTeX companion, p. 85

set("paperwidth",doc_w) # has no effect in pdflatex, so I do this with geometry package
set("paperheight",doc_h) # has no effect in pdflatex, so I do this with geometry package
set("hoffset",margin_outside+outside_trim-1.0)
set("oddsidemargin",gutter)
set("evensidemargin",0.0)
set("textwidth",trim_w-(margin_outside+margin_inside+gutter)) # comes out on the small side

set("voffset",tb_trim+margin_t-1.0)
set("topmargin",0.0)
set("headheight",0.11)
set("headsep",0.22)
set("textheight",trim_h-(margin_t+margin_b+headheight+headsep))
